# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    encoders:
        BackendBundle\Entity\User:
            algorithm: bcrypt
            cost: 4

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        user_db_provider:
            entity:
                class: BackendBundle:User
                property: email

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            provider: user_db_provider
            form_login:
                login_path: /login
                check_path: /login_check
            logout:
                path: logout
                target: /

    access_control:
        - {path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY}
        - {path: ^/register, roles: IS_AUTHENTICATED_ANONYMOUSLY}
        - {path: ^/home, roles: [ROLE_USER, ROLE_ADMIN]}
        - {path: ^/remove-publication, roles: [ROLE_USER, ROLE_ADMIN]}
        - {path: ^/edit-user, roles: [ROLE_USER, ROLE_ADMIN]}
        - {path: ^/user-list, roles: [ROLE_USER, ROLE_ADMIN]}
        - {path: ^/user-search, roles: [ROLE_USER, ROLE_ADMIN]}
        - {path: ^/user, roles: [ROLE_USER, ROLE_ADMIN]}
        - {path: ^/like, roles: [ROLE_USER, ROLE_ADMIN]}
        - {path: ^/unlike, roles: [ROLE_USER, ROLE_ADMIN]}
        - {path: ^/notification, roles: [ROLE_USER, ROLE_ADMIN]}
        - {path: ^/notification/count, roles: [ROLE_USER, ROLE_ADMIN]}
        - {path: ^/notification/remove, roles: [ROLE_USER, ROLE_ADMIN]}
        - {path: ^/private-message, roles: [ROLE_USER, ROLE_ADMIN]}
        - {path: ^/sent, roles: [ROLE_USER, ROLE_ADMIN]}
        - {path: ^/private-message/not-read, roles: [ROLE_USER, ROLE_ADMIN]}
        - {path: ^/following, roles: [ROLE_USER, ROLE_ADMIN]}
        - {path: ^/followed, roles: [ROLE_USER, ROLE_ADMIN]}
        - {path: ^/unfollow, roles: [ROLE_USER, ROLE_ADMIN]}
        - {path: ^/likes, roles: [ROLE_USER, ROLE_ADMIN]}
            # activate different ways to authenticate

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html
            #form_login: ~
