BackendBundle\Entity\User:
    properties:
        firstname:
            - NotBlank: {message: "The first name field can not be blank"}
        lastname:
            - NotBlank: {message: "The last name field can not be blank"}
        nick:
            - NotBlank: {message: "The nickname field can not be blank"}
        email:
            - NotBlank: {message: "The email field can not be blank"}
            - Email:
                message: The email {{ value }} is not valid.
                checkMX: false